// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4bkJaFTqigHymUmVp_xSPM3LlGvD5ARo',
    appId: '1:1026672831328:web:addb3b8251b1f2f51b8c05',
    messagingSenderId: '1026672831328',
    projectId: 'homezs-b3b20',
    authDomain: 'homezs-b3b20.firebaseapp.com',
    storageBucket: 'homezs-b3b20.firebasestorage.app',
    measurementId: 'G-Q17TJE9VTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXjLG-FiusnpFUXkNoAqlGCs8jdS1qoW4',
    appId: '1:1026672831328:android:2ae39d482ff7dc091b8c05',
    messagingSenderId: '1026672831328',
    projectId: 'homezs-b3b20',
    storageBucket: 'homezs-b3b20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqRvQfIt3uwFbCWd-NZLNHYFEzSXRS-0',
    appId: '1:1026672831328:ios:33965ca23f85dd301b8c05',
    messagingSenderId: '1026672831328',
    projectId: 'homezs-b3b20',
    storageBucket: 'homezs-b3b20.firebasestorage.app',
    iosBundleId: 'com.example.homezs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGqRvQfIt3uwFbCWd-NZLNHYFEzSXRS-0',
    appId: '1:1026672831328:ios:33965ca23f85dd301b8c05',
    messagingSenderId: '1026672831328',
    projectId: 'homezs-b3b20',
    storageBucket: 'homezs-b3b20.firebasestorage.app',
    iosBundleId: 'com.example.homezs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4bkJaFTqigHymUmVp_xSPM3LlGvD5ARo',
    appId: '1:1026672831328:web:49d28ea3510c909c1b8c05',
    messagingSenderId: '1026672831328',
    projectId: 'homezs-b3b20',
    authDomain: 'homezs-b3b20.firebaseapp.com',
    storageBucket: 'homezs-b3b20.firebasestorage.app',
    measurementId: 'G-FD9CKQE13H',
  );
}
